version: 2

models:
    - name: pushevents
      description: "Views based on Git data tables"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - not_null

