INSERT INTO {REPOSITORIES_T} (
    archived,
    created_at,
    default_branch,
    description,
    disabled,
    fork,
    forks,
    forks_count,
    full_name,
    has_downloads,
    has_issues,
    has_pages,
    has_projects,
    has_wiki,
    homepage,
    id,
    language,
    license,
    name,
    node_id,
    open_issues,
    open_issues_count,
    owner,
    permissions,
    private,
    pushed_at,
    size,
    stargazers_count,
    updated_at,
    url,
    watchers,
    watchers_count
)
SELECT
    data ->> 'archived' AS archived,
    (data ->> 'created_at')::TIMESTAMP AS created_at,
    data ->> 'default_branch' AS default_branch,
    data ->> 'description' AS description,
    data ->> 'disabled' AS disabled,
    data ->> 'fork' AS fork,
    (data ->> 'forks')::INT AS forks,
    (data ->> 'forks_count')::INT AS forks_count,
    data ->> 'full_name' AS full_name,
    data ->> 'has_downloads' AS has_downloads,
    data ->> 'has_issues' AS has_issues,
    data ->> 'has_pages' AS has_pages,
    data ->> 'has_projects' AS has_projects,
    data ->> 'has_wiki' AS has_wiki,
    data ->> 'homepage' AS homepage,
    (data ->> 'id')::BIGINT AS id,
    data ->> 'language' AS language,
    data ->> 'license' AS license,
    data ->> 'name' AS name,
    data ->> 'node_id' AS node_id,
    (data ->> 'open_issues')::INT AS open_issues,
    (data ->> 'open_issues_count')::INT AS open_issues_count,
    data -> 'owner' AS owner,
    data -> 'permissions' AS permissions,
    data ->> 'private' AS private,
    (data ->> 'pushed_at')::TIMESTAMP AS pushed_at,
    (data ->> 'size')::INT AS size,
    (data ->> 'stargazers_count')::INT AS stargazers_count,
    (data ->> 'updated_at')::TIMESTAMP AS updated_at,
    data ->> 'url' AS url,
    (data ->> 'watchers')::INT AS watchers,
    (data ->> 'watchers_count')::INT AS watchers_count
FROM staging
ON CONFLICT (id, node_id) DO UPDATE
    SET
        archived = excluded.archived

