CREATE TABLE IF NOT EXISTS {ORGANIZATION_T} (
    avatar_url    VARCHAR,
    company    VARCHAR,
    created_at    TIMESTAMP,
    description    VARCHAR,
    email    VARCHAR,
    followers    INTEGER,
    following    INTEGER,
    has_organization_projects    VARCHAR,
    has_repository_projects    VARCHAR,
    id    BIGINT,
    is_verified    VARCHAR,
    location    VARCHAR,
    login    VARCHAR,
    name    VARCHAR,
    node_id    VARCHAR,
    public_gists    INTEGER,
    public_members_url    VARCHAR,
    public_repos    INTEGER,
    repos_url    VARCHAR,
    twitter_username    VARCHAR,
    type    VARCHAR,
    updated_at    TIMESTAMP,
    PRIMARY KEY(id, node_id)
)