CREATE TABLE IF NOT EXISTS {REPOSITORIES_T} (
    archived    VARCHAR,
    created_at    TIMESTAMP,
    default_branch    VARCHAR,
    description    VARCHAR,
    disabled    VARCHAR,
    fork    VARCHAR,
    forks    INTEGER,
    forks_count    INTEGER,
    full_name    VARCHAR,
    has_downloads    VARCHAR,
    has_issues    VARCHAR,
    has_pages    VARCHAR,
    has_projects    VARCHAR,
    has_wiki    VARCHAR,
    homepage    VARCHAR,
    id    BIGINT,
    language    VARCHAR,
    license    VARCHAR,
    name    VARCHAR,
    node_id    VARCHAR,
    open_issues    INTEGER,
    open_issues_count    INTEGER,
    owner    JSON,
    permissions    JSON,
    private    VARCHAR,
    pushed_at    TIMESTAMP,
    size    INTEGER,
    stargazers_count    INTEGER,
    updated_at    TIMESTAMP,
    url    VARCHAR,
    watchers    INTEGER,
    watchers_count    INTEGER,
    PRIMARY KEY(id, node_id)
)